import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Play } from "lucide-react";
import { Eyebrow, Reveal } from "@/components/ui";
import { media } from "@/data/media";
import { projects } from "@/data/projects";
export const metadata: Metadata = { title: "Wedding Film", description: "Wedding film cinematografici e autentici firmati Flight P.R.", alternates: { canonical: "/film" } };
export default function Film() { const films = projects.filter(p=>p.category.includes("film")); return <main id="main"><section className="inner-hero film-hero"><Image src={media.showreelPoster} fill priority unoptimized sizes="100vw" alt="Wedding film, poster stock temporaneo"/><div className="hero-overlay"/><Reveal><Eyebrow>Flight films</Eyebrow><h1>Ogni storia<br/><em>ha il proprio ritmo.</em></h1><p>Voci, movimenti e silenzi. Il matrimonio torna a vivere come un film.</p></Reveal><button className="hero-play" aria-label="Showreel placeholder"><Play fill="currentColor"/> Showreel in arrivo</button></section><section className="section film-intro"><Eyebrow>Il nostro cinema</Eyebrow><h2>Non una cronaca.<br/><em>Una presenza.</em></h2><p>Montiamo ciò che accade senza interromperlo: l’atmosfera del luogo, le parole, gli incontri e tutto quello che spesso sfugge mentre lo si vive.</p></section><section className="film-grid">{films.map((p,i)=><Link href={`/portfolio/${p.slug}`} key={p.slug} className="film-card"><Image src={p.cover} fill unoptimized sizes="(max-width: 768px) 100vw, 50vw" alt={`${p.title}, film demo con poster stock`}/><div className="hero-overlay"/><span className="film-index">0{i+1}</span><div><small>Film demo · contenuto placeholder</small><h2>{p.title}</h2><p>{p.location} · Durata da definire</p></div><Play className="film-play"/></Link>)}</section><section className="simple-cta"><h2>Il vostro giorno, in movimento.</h2><Link href="/contatti" className="button-primary">Raccontateci la vostra storia <ArrowRight/></Link></section></main>; }
