import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Eyebrow, Reveal } from "@/components/ui";
import { media } from "@/data/media";
export const metadata: Metadata = { title: "Matrimoni", description: "Fotografia, wedding film e drone per matrimoni autentici in tutta Italia.", alternates: { canonical: "/matrimoni" } };
const chapters = [["Preparativi", media.wedding.details], ["Cerimonia", media.wedding.ceremony], ["Ritratto", media.wedding.couple], ["Ricevimento", media.wedding.reception], ["Party", media.wedding.party], ["Dettagli", media.wedding.tuscany]];
export default function Weddings() { return <main id="main"><section className="inner-hero"><Image src={media.wedding.puglia} fill priority unoptimized sizes="100vw" alt="Cerimonia elegante, immagine stock temporanea"/><div className="hero-overlay"/><Reveal><Eyebrow>Matrimoni · Fotografia · Film</Eyebrow><h1>Un giorno.<br/><em>Una storia irripetibile.</em></h1><p>Non costruiamo momenti. Li riconosciamo.</p></Reveal></section><section className="section editorial-intro"><Eyebrow>Reportage contemporaneo</Eyebrow><h2>Presenti in ogni istante.<br/><em>Discreti in ogni immagine.</em></h2><p>Dal silenzio dei preparativi al ritmo del party: fotografia, cinema e riprese aeree lavorano insieme per restituire la giornata nella sua interezza.</p></section><section className="chapter-grid">{chapters.map(([title, src], i)=><figure key={title} className={`chapter chapter-${i+1}`}><Image src={src} fill unoptimized sizes="(max-width: 768px) 100vw, 50vw" alt={`${title}, fotografia stock temporanea`}/><figcaption><span>0{i+1}</span>{title}</figcaption></figure>)}</section><section id="drone" className="split-feature"><div className="split-image"><Image src={media.drone} fill unoptimized sizes="(max-width: 768px) 100vw, 58vw" alt="Ripresa aerea di una location italiana, stock temporanea"/></div><Reveal><Eyebrow>Drone</Eyebrow><h2>Il luogo diventa<br/>parte del racconto.</h2><p>Droni di ultima generazione per immagini fluide, nitide e coerenti con il linguaggio del film.</p></Reveal></section><section className="simple-cta"><h2>Ogni storia ha il proprio ritmo.</h2><Link href="/contatti" className="button-primary">Parliamo della vostra <ArrowRight/></Link></section></main>; }
