import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, Camera, Play } from "lucide-react";
import { media } from "@/data/media";
import { services } from "@/data/services";
import { PortfolioGrid } from "@/components/portfolio-grid";
import { Eyebrow, Reveal, TextLink } from "@/components/ui";

export default function Home() {
  return <main id="main">
    <section className="hero home-hero"><Image src={media.hero} fill unoptimized priority sizes="100vw" alt="Matrimonio italiano, immagine stock temporanea" /><div className="hero-overlay"/><div className="hero-grain"/><div className="hero-content"><Reveal><Eyebrow>Flight Personal Recording · Italia</Eyebrow><h1>Ci sono momenti<br/>che non tornano.<br/><em>Le immagini restano.</em></h1><p>Fotografia, cinema e riprese aeree per raccontare matrimoni attraverso immagini autentiche, eleganti e senza tempo.</p><div className="hero-actions"><Link href="/matrimoni" className="button-primary">Scopri i nostri matrimoni <ArrowRight/></Link><Link href="#showreel" className="button-ghost"><Play/> Guarda lo showreel</Link></div></Reveal></div><a href="#manifesto" className="scroll-cue">Scroll to discover <ArrowDown/></a></section>
    <section id="manifesto" className="section manifesto"><Reveal className="manifesto-copy"><Eyebrow>Il vostro giorno, il nostro sguardo</Eyebrow><h2>Ogni storia merita<br/>il proprio <em>film.</em></h2><p>Fotografi, videografi e dronisti uniti dalla stessa sensibilità. Lavoriamo in tutta Italia per riconoscere emozioni vere e trasformarle in ricordi senza tempo.</p><TextLink href="/chi-siamo">Il nostro modo di vedere</TextLink></Reveal><Reveal className="manifesto-image" delay={.1}><Image src={media.manifesto} fill unoptimized sizes="(max-width: 768px) 100vw, 42vw" alt="Dettaglio di una cerimonia, immagine stock temporanea"/></Reveal><div className="flight-line" aria-hidden="true"/></section>
    <section className="section stories"><div className="section-heading"><Reveal><Eyebrow>Storie · portfolio demo</Eyebrow><h2>Ogni matrimonio<br/>è diverso.</h2></Reveal><TextLink href="/portfolio">Esplora il portfolio</TextLink></div><PortfolioGrid compact/></section>
    <section id="showreel" className="showreel"><Image src={media.showreelPoster} fill unoptimized sizes="100vw" alt="Fotogramma wedding film, immagine stock temporanea"/><div className="hero-overlay"/><div className="showreel-content"><Eyebrow>Flight films · contenuto placeholder</Eyebrow><h2>Premi play.<br/><em>Il resto è emozione.</em></h2><button className="play-button" aria-label="Showreel non ancora disponibile"><Play fill="currentColor"/><span>Showreel<br/>in arrivo</span></button></div></section>
    <section className="section services"><div className="section-heading sticky-title"><div><Eyebrow>I nostri servizi</Eyebrow><h2>Un solo team.<br/><em>Ogni prospettiva.</em></h2></div></div><div className="service-list">{services.map((s) => <article className="service" key={s.number}><div className="service-image"><Image src={s.image} fill unoptimized sizes="(max-width: 768px) 100vw, 48vw" alt={`${s.title}, immagine stock temporanea`}/></div><div className="service-copy"><span>{s.number}</span><h3>{s.title}</h3><p>{s.copy}</p></div></article>)}</div></section>
    <section className="numbers" aria-label="I numeri Flight P.R.">{[["75+", "Matrimoni"], ["180+", "Feste"], ["20+", "Eventi"]].map(([n,l]) => <Reveal key={l}><strong>{n}</strong><span>{l} · 2025</span></Reveal>)}</section>
    <section className="section why"><Reveal><Eyebrow>Perché Flight</Eyebrow><h2>Il vostro matrimonio.<br/><em>Mai quello di qualcun altro.</em></h2></Reveal><div className="why-grid">{[["01","Autenticità","Niente pose forzate. Cerchiamo gesti, sguardi e momenti reali."],["02","Unicità","Ogni coppia ha un linguaggio diverso. Anche il racconto deve averlo."],["03","Creatività","Fotografia, cinema e montaggio diventano parti della stessa narrazione."],["04","Puntualità","Rispettiamo il ritmo della giornata, i programmi e ogni momento che conta."]].map(([n,t,c])=><Reveal key={n} className="why-item"><span>{n}</span><h3>{t}</h3><p>{c}</p></Reveal>)}</div></section>
    <section id="drone" className="drone"><Image src={media.drone} fill unoptimized sizes="100vw" alt="Paesaggio italiano visto dall’alto, immagine stock temporanea"/><div className="hero-overlay"/><Reveal className="drone-copy"><Eyebrow>Drone</Eyebrow><h2>Un’altra prospettiva<br/><em>sulla vostra storia.</em></h2><p>Non semplici riprese aeree: il paesaggio entra nel film e diventa parte del racconto.</p><TextLink href="/matrimoni#drone" inverse>Scopri le riprese drone</TextLink></Reveal></section>
    <section className="section locations"><Eyebrow>Destination stories</Eyebrow><h2>Dalla città al mare.<br/>Dalla masseria alla villa.</h2><div className="location-row">{["Roma","Puglia","Toscana","Costiera Amalfitana"].map((l,i)=><div key={l}><span>0{i+1}</span><h3>{l}</h3><p>Progetto demo</p></div>)}</div><p className="location-note">Flight P.R. lavora da anni in tutto il territorio italiano, adattando il racconto all’identità di ogni luogo.</p></section>
    <section className="section process"><div><Eyebrow>Il metodo Flight P.R.</Eyebrow><h2>Come<br/><em>lavoriamo.</em></h2></div><ol>{[["Conosciamoci","Ascoltiamo chi siete, l’evento e il racconto che desiderate."],["Progettiamo","Definiamo stile, tempi, location e copertura della giornata."],["Viviamo il giorno","Raccontiamo ogni momento in modo naturale, discreto e presente."],["Il vostro racconto","Selezione, color grading, montaggio e consegna finale."]].map(([t,c],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div></li>)}</ol></section>
    <section className="social"><div className="social-heading"><Eyebrow>Follow the stories</Eyebrow><a href="https://instagram.com/flight_pr"><Camera/> @flight_pr</a></div><div className="social-grid">{[media.wedding.details, media.wedding.party, media.wedding.couple, media.wedding.reception].map((src,i)=><a href="https://instagram.com/flight_pr" key={src} aria-label={`Camera Flight P.R. — anteprima ${i+1}`}><Image src={src} fill unoptimized sizes="(max-width: 768px) 50vw, 25vw" alt="Moodboard stock temporaneo"/></a>)}</div></section>
    <section className="final-cta"><Image src={media.finalCta} fill unoptimized sizes="100vw" alt="Coppia durante il ricevimento, immagine stock temporanea"/><div className="hero-overlay"/><Reveal><Eyebrow>Iniziamo da qui</Eyebrow><h2>Avete già scelto il giorno.<br/><em>Ora scegliete come ricordarlo.</em></h2><p>Raccontateci il vostro matrimonio. Al resto pensiamo insieme.</p><div><Link className="button-primary" href="/contatti">Raccontateci la vostra storia <ArrowRight/></Link><a className="button-ghost" href="https://wa.me/393713991692">WhatsApp</a></div></Reveal></section>
  </main>;
}
