"use client";
import { AnimatePresence, motion, useMotionValueEvent, useScroll } from "framer-motion";
import { ArrowUpRight, Camera, Menu, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { media, stockNotice } from "@/data/media";
const nav = [["Matrimoni", "/matrimoni"], ["Film", "/film"], ["Portfolio", "/portfolio"], ["Chi siamo", "/chi-siamo"]];
export function Navbar() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const { scrollY } = useScroll();
  useMotionValueEvent(scrollY, "change", (y) => setScrolled(y > 40));
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]);
  const mobile = [["Home", "/"], ["Matrimoni", "/matrimoni"], ["Foto", "/portfolio?filter=fotografia"], ["Film", "/film"], ["Drone", "/matrimoni#drone"], ["Portfolio", "/portfolio"], ["Chi siamo", "/chi-siamo"], ["Contatti", "/contatti"]];
  return <><header className={`navbar ${scrolled ? "is-scrolled" : ""}`}><Link href="/" aria-label="Flight P.R. — Home" className="brand"><Image src={media.logo} width={200} height={75} unoptimized alt="Flight P.R." priority /></Link><nav aria-label="Navigazione principale">{nav.map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</nav><Link href="/contatti" className="nav-cta">Parliamone <ArrowUpRight size={15} /></Link><button className="menu-trigger" onClick={() => setOpen(true)} aria-label="Apri menu" aria-expanded={open}><Menu /></button></header>
    <AnimatePresence>{open && <motion.div className="mobile-menu" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><div className="mobile-menu-top"><Image src={media.logo} width={200} height={75} unoptimized alt="Flight P.R." /><button onClick={() => setOpen(false)} aria-label="Chiudi menu"><X /></button></div><nav aria-label="Menu mobile">{mobile.map(([label, href], i) => <motion.div key={href} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .04 * i }}><Link href={href} onClick={() => setOpen(false)}><span>0{i + 1}</span>{label}</Link></motion.div>)}</nav><a className="mobile-whatsapp" href="https://wa.me/393713991692?text=Ciao,%20vorrei%20avere%20pi%C3%B9%20informazioni!">Scrivici su WhatsApp <ArrowUpRight /></a></motion.div>}</AnimatePresence></>;
}
export function Footer() { return <footer className="footer"><div className="stock-notice">Anteprima creativa · {stockNotice}</div><div className="footer-grid"><div className="footer-brand"><Image src={media.mark} width={180} height={180} unoptimized alt="Simbolo Flight P.R." /><p>Flight Personal Recording</p><span>Fotografia · Film · Drone</span></div><div><h3>Esplora</h3><Link href="/matrimoni">Matrimoni</Link><Link href="/film">Film</Link><Link href="/portfolio">Portfolio</Link><Link href="/chi-siamo">Chi siamo</Link></div><div><h3>Servizi</h3><Link href="/matrimoni">Fotografia</Link><Link href="/film">Video</Link><Link href="/matrimoni#drone">Drone</Link><Link href="/portfolio?filter=eventi">Eventi</Link></div><div><h3>Contatti</h3><a href="mailto:flight.personal.recording@gmail.com">flight.personal.recording<br/>@gmail.com</a><a href="tel:+393713991692">+39 371 399 1692</a><a href="https://instagram.com/flight_pr"><Camera size={16}/> @flight_pr</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Flight P.R. · P.IVA 18244501005</span><div><Link href="/privacy">Privacy</Link><Link href="/cookie-policy">Cookie</Link></div></div><div className="footer-wordmark" aria-hidden="true">FLIGHT P.R.</div></footer>; }
export function SiteShell({ children }: { children: React.ReactNode }) { return <><Navbar />{children}<Footer /></>; }
