import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, Play } from "lucide-react";
import { DemoBadge, Eyebrow } from "@/components/ui";
import { getProject, projects } from "@/data/projects";
export function generateStaticParams() { return projects.map(p=>({slug:p.slug})); }
export async function generateMetadata({ params }: { params: Promise<{slug:string}> }): Promise<Metadata> { const p=getProject((await params).slug); return { title: p ? `${p.title} — Progetto demo` : "Progetto", robots: p?.demo ? { index: false, follow: true } : undefined }; }
export default async function ProjectPage({ params }: { params: Promise<{slug:string}> }) { const project=getProject((await params).slug); if(!project) notFound(); return <main id="main"><section className="project-hero"><Image src={project.cover} fill priority unoptimized sizes="100vw" alt={`${project.title}, immagine stock temporanea`}/><div className="hero-overlay"/><Link href="/portfolio" className="back-link"><ArrowLeft/> Portfolio</Link><div><DemoBadge/><h1>{project.title}</h1><p>{project.location} · {project.year}</p></div></section><section className="project-intro"><div><Eyebrow>Nota importante</Eyebrow><h2>Una storia<br/><em>dimostrativa.</em></h2></div><div><p>{project.description}</p><p>{project.credits}. Questo progetto non rappresenta un matrimonio realmente realizzato da Flight P.R.</p></div></section><section className="project-gallery">{project.images.map((src,i)=><figure key={`${src}-${i}`}><Image src={src} fill unoptimized sizes="(max-width: 768px) 100vw, 60vw" alt={`Gallery demo ${project.title}, immagine stock ${i+1}`}/></figure>)}</section><section className="video-placeholder"><Play/><Eyebrow>Project film</Eyebrow><h2>Video originale<br/>in arrivo.</h2><p>Componente predisposto per accogliere il film Flight P.R.</p></section><section className="simple-cta"><h2>Volete raccontare la vostra?</h2><Link href="/contatti" className="button-primary">Parliamone <ArrowRight/></Link></section></main>; }
